name: choof_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+4
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html


environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  get_storage: ^2.0.3
  youtube_player_flutter: ^8.0.0
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.6
  cloud_firestore: ^3.1.7
  google_sign_in: ^5.2.3
  flutter_facebook_auth: ^4.1.2
  http: ^0.13.4
  twitter_login: ^4.1.0
  flutter_local_notifications: ^9.4.0
  rxdart: ^0.27.3
  font_awesome_flutter: ^10.1.0
  flutter_email_sender: ^5.1.0
  pull_to_refresh: ^2.0.0
  url_launcher: ^6.1.0
  the_apple_sign_in: ^1.1.1
  flutter_launcher_icons: ^0.9.3
  
flutter_icons:
  android: true
  ios: false
  image_path: "assets/logos/ic_launcher.png"
  # adaptive_icon_foreground: "assets/logos/ic_launcher.png"
  # adaptive_icon_background: "#000000"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
